### ISSUE TITLE
$PATH is set incorrectly when using multiple folders

### ISSUE THREAD

**Issue by atrawog** [mamba-org/vscode-micromamba#11]
### Environment

Operating system: Arch Linux
Node: v17.3.0
VS Code: 1.62.2

### Steps to Reproduce

- Add FolderA to Workspace
- Add FolderB to Workspace
- Open Terminal for FolderB

### Expected Behavior

$PATH should be set to FolderB/.micromamba

### Actual Behavior

$PATH is always set to FolderA/.micromamba

To set PATH to FolderB/.micromamba you have to remove all folders until FolderB is on top of your folder list.

**Comment by corker** [comment]
Seems to be similar to NiX approach and I like it a lot! I don't think VSCode supports terminals per folder out of the box. Of course it's possible to work it around but I see a with this approach - how to indicate to a user what is an active folder now. This is a complex problem and I don't see a good solution that would be clear for developers of every level and background. The goal of this extension is to provide an easy way to "clone and run" a git repository on my local machine. I want to take a different path at least until VSCode implements support for "active workspace folder". I suggest to stick with the first folder in the workspace as a target folder for the extension. Then it's always clear where to look for environment.yml file and .micromamba directory. I'll update the docs to make it clear because it's already working this way.
